services:
  Apipa169\DataTablesCompatibilityBundle\Handler\DataTablesCompatibilityHandler:
    tags:
      - { name: kernel.event_listener, event: kernel.response }
      - { name: kernel.event_listener, event: kernel.request }