services:
  Apipa169\DataTablesCompatibilityBundle\Handler\DataTablesCompatibilityHandler:
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: kernel.request }
  Apipa169\DataTablesCompatibilityBundle\Handler\DataTablesDrawHandler:
    tags:
      - { name: kernel.event_listener, event: kernel.response }